smool_url/models.py
from datetime import datetime
import random
import string
from .extensions import db

class Url(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    long_url = db.Column(db.String(256))
    short_url = db.Column(db.String(20), unique=True)
    create_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # generate a random alias if no alias
        if len(self.short_url) == 0:
            self.short_url = self.generate_short_url()

    def generate_short_url(self):
        url = ("".join(random.choices(string.ascii_letters, k=5)))
        link = self.query.filter_by(short_url=url).first()

        if link:
            return self.generate_short_url()
        return url

smool_url/__init__.py
from flask import Flask

from .extensions import db
from .routes import shorturl

def create_app(config_file='settings.py'):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)

    db.init_app(app)
    app.register_blueprint(shorturl)
    return app

smool_url/routes.py
from flask import Blueprint, render_template, request, redirect
from .extensions import db
from .models import Url

shorturl = Blueprint('shorturl', __name__, template_folder='templates')

@shorturl.route('/')
def index():
    return render_template('index.html')

@shorturl.route('/<short_url>')
def redirect_url(short_url):
    url = Url.query.filter_by(short_url=short_url).first_or_404()
    return redirect(url.long_url)

@shorturl.route('/', methods=['POST'])
def create():
    long_url = request.form['long_url']
    short_url = request.form['short_url']
    
    # error checking
    if db.session.query(db.exists().where(Url.short_url == short_url)).scalar():
        return render_template('url_existed.html')

    url = Url(long_url=long_url, short_url=short_url)
    db.session.add(url)
    db.session.commit()
    
    return render_template('url_created.html', new_url=url.short_url)

@shorturl.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

smool_url/templates/index.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <h2 style="padding-top: 20px;">SmoolURL</h2>

    <form method="POST" action="{{ url_for('shorturl.create') }}">
        <div class="form-group">
            <label for="inputURL">Original URL</label>
            <input type="url" name="long_url" class="form-control" id="inputURL" aria-describedby="inputURLHelp" required>
        </div>

        <label for="basic-url">Custom Alias (Optional)</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="custom-alias">https://smoolurl.com/</span>
            </div>
            <input type="text" name="short_url" class="form-control" id="basic-url" aria-describedby="custom-alias" maxlength="20" required>
        </div>
        <p style="font-size: small;" class="form-text text-muted">Alias cannot exceed 20 characters</p>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

smool_url/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>SmoolURL</title>
</head>

<body>
    {% block body %}{% endblock %}

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

smool_url/templates/url_created.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <h2 style="padding-top: 20px;">SmoolURL</h2>
    <p style="padding-top: 10px;">You can now access with the new url at
        <a href="{{ url_for('shorturl.redirect_url', short_url=new_url, _external=True) }}">
            {{ url_for('shorturl.redirect_url', short_url=new_url, _external=True) }}
        </a>
    </p>
    <a href="{{ url_for('shorturl.index') }}">Back to Home</a>
</div>
</div>
{% endblock %}

smool_url/templates/url_existed.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <h2 style="padding-top: 20px;">SmoolURL</h2>
        <p style="padding-top: 10px;">Alias has been used</p>
        <a href="{{ url_for('shorturl.index') }}">Back to Home</a>
    </div>
</div>
{% endblock %}